wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: huggingface
    huggingface_version: 4.20.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.5
    start_time: 1659581893
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      4: 3.10.5
      5: 0.12.16
      6: 4.20.1
      8:
      - 3
      - 5
