wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.16
    framework: huggingface
    huggingface_version: 4.20.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.5
    start_time: 1659592573
    t:
      1:
      - 1
      - 11
      - 49
      - 55
      2:
      - 1
      - 11
      - 49
      - 55
      3:
      - 1
      - 3
      - 19
      4: 3.10.5
      5: 0.12.16
      6: 4.20.1
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 64
epochs:
  desc: null
  value: 15
log_interval:
  desc: null
  value: 10
lr:
  desc: null
  value: 0.001
no_cuda:
  desc: null
  value: false
test_batch_size:
  desc: null
  value: 10
